#define NUM_COUNTRY 253
char *country[] = {"Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa",
"Andorra", "Angola", "Anguilla", "Antarctica", "Antigua and Barbuda",
"Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan",
"Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium",
"Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegovina",
"Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory",
"British Virgin Islands", "Brunei Darussalam", "Bulgaria", "Burkina Faso",
"Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands",
"Central African Republic", "Chad", "Chile", "China", "Christmas Island",
"Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo (Brazzaville)",
"Democratic Republic of the Congo", "Cook Islands", "Costa Rica", "Croatia",
"Cuba", "Cyprus", "Czech Republic", "Côte d'Ivoire", "Denmark",
"Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
"El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia",
"Falkland Islands (Malvinas)", "Faroe Islands", "Fiji", "Finland",
"France", "French Guiana", "French Polynesia", "French Southern Territories",
"Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar",
"Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala",
"Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard and Mcdonald Islands",
"Holy See (Vatican City State)", "Honduras", "Hong Kong, SAR China",
"Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of",
"Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica",
"Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati",
"Korea (North)", "Korea (South)", "Kuwait", "Kyrgyzstan", "Lao PDR",
"Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein",
"Lithuania", "Luxembourg", "Macao, SAR China", "Macedonia, Republic of",
"Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
"Marshall Islands", "Martinique", "Mauritania", "Mauritius",
"Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova",
"Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco",
"Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands",
"Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua",
"Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands",
"Norway", "Oman", "Pakistan", "Palau", "Palestinian Territory",
"Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
"Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania",
"Russian Federation", "Rwanda", "Réunion", "Saint Helena", "Saint Kitts and Nevis",
"Saint Lucia", "Saint Pierre and Miquelon", "Saint Vincent and Grenadines",
"Saint-Barthélemy", "Saint-Martin (French part)", "Samoa", "San Marino",
"Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia",
"Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia",
"Solomon Islands", "Somalia", "South Africa", "South Georgia and the South Sandwich Islands",
"South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Svalbard and Jan Mayen Islands",
"Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic (Syria)",
"Taiwan, Republic of China", "Tajikistan", "Tanzania, United Republic of",
"Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad and Tobago",
"Tunisia", "Turkey", "Turkmenistan", "Turks and Caicos Islands",
"Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
"United States of America", "Uruguay", "US Minor Outlying Islands",
"Uzbekistan", "Vanuatu", "Venezuela (Bolivarian Republic)",
"Viet Nam", "Virgin Islands, US", "Wallis and Futuna Islands",
"Western Sahara", "Yemen", "Zambia", "Zimbabwe",
"USA", "US", "South Korea", "North Korea", "Venezuela", "DRC"};

 char *countrycode[]={"AFG", "ALA", "ALB", "DZA", "ASM", "AND", "AGO", "AIA", "ATA",
 "ATG", "ARG", "ARM", "ABW", "AUS", "AUT", "AZE", "BHS", "BHR",
 "BGD", "BRB", "BLR", "BEL", "BLZ", "BEN", "BMU", "BTN", "BOL",
 "BIH", "BWA", "BVT", "BRA", "IOT", "VGB", "BRN", "BGR", "BFA",
 "BDI", "KHM", "CMR", "CAN", "CPV", "CYM", "CAF", "TCD", "CHL",
 "CHN", "CXR", "CCK", "COL", "COM", "COG", "COD", "COK", "CRI",
 "HRV", "CUB", "CYP", "CZE", "CIV", "DNK", "DJI", "DMA", "DOM",
 "ECU", "EGY", "SLV", "GNQ", "ERI", "EST", "ETH", "FLK", "FRO",
 "FJI", "FIN", "FRA", "GUF", "PYF", "ATF", "GAB", "GMB", "GEO",
 "DEU", "GHA", "GIB", "GRC", "GRL", "GRD", "GLP", "GUM", "GTM",
 "GGY", "GIN", "GNB", "GUY", "HTI", "HMD", "VAT", "HND", "HKG",
 "HUN", "ISL", "IND", "IDN", "IRN", "IRQ", "IRL", "IMN", "ISR",
 "ITA", "JAM", "JPN", "JEY", "JOR", "KAZ", "KEN", "KIR", "PRK",
 "KOR", "KWT", "KGZ", "LAO", "LVA", "LBN", "LSO", "LBR", "LBY",
 "LIE", "LTU", "LUX", "MAC", "MKD", "MDG", "MWI", "MYS", "MDV",
 "MLI", "MLT", "MHL", "MTQ", "MRT", "MUS", "MYT", "MEX", "FSM",
 "MDA", "MCO", "MNG", "MNE", "MSR", "MAR", "MOZ", "MMR", "NAM",
 "NRU", "NPL", "NLD", "ANT", "NCL", "NZL", "NIC", "NER", "NGA",
 "NIU", "NFK", "MNP", "NOR", "OMN", "PAK", "PLW", "PSE", "PAN",
 "PNG", "PRY", "PER", "PHL", "PCN", "POL", "PRT", "PRI", "QAT",
 "ROU", "RUS", "RWA", "REU", "SHN", "KNA", "LCA", "SPM", "VCT",
 "BLM", "MAF", "WSM", "SMR", "STP", "SAU", "SEN", "SRB", "SYC",
 "SLE", "SGP", "SVK", "SVN", "SLB", "SOM", "ZAF", "SGS", "SSD",
 "ESP", "LKA", "SDN", "SUR", "SJM", "SWZ", "SWE", "CHE", "SYR",
 "TWN", "TJK", "TZA", "THA", "TLS", "TGO", "TKL", "TON", "TTO",
 "TUN", "TUR", "TKM", "TCA", "TUV", "UGA", "UKR", "ARE", "GBR",
 "USA", "URY", "UMI", "UZB", "VUT", "VEN", "VNM", "VIR", "WLF",
 "ESH", "YEM", "ZMB", "ZWE",
 "USA", "USA", "KOR", "PRK", "VEN", "DRC"};
